### ISSUE TITLE
zaemyung/ml docker image has trouble accessing graphics card

### ISSUE THREAD

**Issue by kooryan** [zaemyung/dockerfiles#1]
* Switching to Python version 3.8.5 and CUDA version 11.2 seems to allow for pytorch to detect GPU for some reason

**Comment by zaemyung** [comment]
I think the issue occurs when the GPU driver version is mismatched with that of the Docker container (c.f. https://stackoverflow.com/questions/63960319/does-it-matter-if-the-version-of-cuda-on-docker-is-different-from-the-version-of)

So either an upgrade of the host GPU driver version or a downgrade of that of the container (as you did) is required.
